Fix mysql8 test (#2576)
Reviewed-on: https://gitea.com/xorm/xorm/pulls/2576
Reviewed-by: Lunny Xiao <xiaolunwen@gmail.com>
Co-authored-by: Zettat123 <zettat123@gmail.com>
Co-committed-by: Zettat123 <zettat123@gmail.com>

diff --git a/.gitea/workflows/test-mysql8.yml b/.gitea/workflows/test-mysql8.yml
--- a/.gitea/workflows/test-mysql8.yml
+++ b/.gitea/workflows/test-mysql8.yml
@@ -15,6 +15,14 @@ jobs:
       - uses: actions/setup-go@v5
         with:
           go-version-file: 'go.mod'
+      - name: wait for mysql8 service
+        run: |
+          for i in $(seq 1 15); do
+            (echo > /dev/tcp/mysql8/3306) &>/dev/null && echo "MySQL is ready!" && break
+            echo "Waiting for MySQL... ($i/15)"
+            [ $i -eq 15 ] && echo "MySQL failed to start in time!" && exit 1
+            sleep 1
+          done
       - name: test mysql8
         env:
           TEST_MYSQL_HOST: mysql8
